# Generated by Django 3.0.5 on 2020-04-07 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('phonenum', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('coupon', models.ImageField(upload_to='{title}')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='eoiku.User_info')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
