# Generated by Django 3.0.5 on 2020-04-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eoiku', '0003_auto_20200407_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
