# Generated by Django 3.0.5 on 2020-04-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eoiku', '0005_coupon_post_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eoiku.Coupon'),
        ),
    ]
