# Generated by Django 3.0.5 on 2020-04-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coupon',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='period',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
