# Generated by Django 3.0.5 on 2020-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('phonenum', models.CharField(max_length=13)),
            ],
        ),
    ]
